import {Editor} from '@tiptap/core';
import {extensions} from './document.js';
const $=id=>document.getElementById(id);
let state={attachments:[],agents:[],columns:[]}, loading=false;
const post=(type,data={})=>window.webkit?.messageHandlers.taskEditor.postMessage({type,...data});
const editor=new Editor({element:$('editor'),extensions:extensions(),content:'',editorProps:{attributes:{'aria-label':'Task description',role:'textbox','aria-multiline':'true'},handlePaste:(_,event)=>importFiles(event.clipboardData?.files,true),handleDrop:(_,event)=>importFiles(event.dataTransfer?.files,true)},onUpdate:()=>changed(),onSelectionUpdate:()=>updateToolbar()});
function changed(){if(!loading){$('save-status').textContent='Saving…';post('change',{title:$('title').value,body:editor.getMarkdown()});}updateToolbar();}
function updateToolbar(){document.querySelectorAll('[data-command]').forEach(b=>b.classList.toggle('active',editor.isActive(b.dataset.command)));}
function showError(message){$('error').textContent=message;$('error').hidden=!message;}
function importFiles(files,inline){const images=[...(files||[])].filter(f=>f.type.startsWith('image/'));if(!images.length)return false;for(const file of images){if(file.size>32*1024*1024){showError('This image is larger than 32 MB. Choose a smaller image.');continue;}const reader=new FileReader();reader.onload=()=>post('image',{data:String(reader.result).split(',')[1],filename:file.name,typeHint:file.type,inline});reader.onerror=()=>showError('The image could not be read.');reader.readAsDataURL(file);}return true;}
function optionButton({label,detail='',selected=false,onChoose}){const b=document.createElement('button');b.className='select-option';b.type='button';b.setAttribute('role','option');b.setAttribute('aria-selected',String(selected));const copy=document.createElement('span');copy.className='option-copy';const title=document.createElement('span');title.textContent=label;copy.append(title);if(detail){const small=document.createElement('small');small.textContent=detail;copy.append(small);}const check=document.createElement('span');check.className='option-check';check.textContent=selected?'✓':'';check.setAttribute('aria-hidden','true');b.append(copy,check);b.onclick=onChoose;return b;}
function closePicker(picker,trigger,restoreFocus=false){picker.hidden=true;trigger.setAttribute('aria-expanded','false');trigger.classList.remove('open');if(restoreFocus)trigger.focus();}
function closeSelects(except){for(const [trigger,picker] of [[$('status'),$('status-picker')],[$('assignee'),$('agent-picker')]])if(picker!==except&&!picker.hidden)closePicker(picker,trigger);}
function openPicker(picker,trigger,{refresh=false,focusSearch=false}={}){closeSelects(picker);picker.hidden=false;trigger.setAttribute('aria-expanded','true');trigger.classList.add('open');if(refresh)post('refreshAgents');requestAnimationFrame(()=>{const selected=picker.querySelector('[aria-selected="true"]');if(focusSearch)$('agent-search').focus();else (selected||picker.querySelector('.select-option'))?.focus();});}
function togglePicker(picker,trigger,options){picker.hidden?openPicker(picker,trigger,options):closePicker(picker,trigger,true);}
function renderStatus(){const current=state.columns.find(c=>c.id===state.columnID);$('status-value').textContent=current?.name||'Choose status';$('status-options').replaceChildren(...state.columns.map(column=>optionButton({label:column.name,selected:column.id===state.columnID,onChoose:()=>{state.columnID=column.id;renderStatus();closePicker($('status-picker'),$('status'),true);post('status',{columnID:column.id});}})));}
function renderAgents(){const query=$('agent-search').value.toLowerCase();$('agent-options').replaceChildren();const add=(label,detail,id)=>$('agent-options').append(optionButton({label,detail,selected:id===state.assigneeID,onChoose:()=>{state.assigneeID=id;state.assigneeName=label;renderAssignee();closePicker($('agent-picker'),$('assignee'),true);post('assign',{agentID:id});}}));add('Unassigned','',null);for(const a of state.agents.filter(a=>(a.name+' '+a.detail).toLowerCase().includes(query)))add(a.name,a.detail,a.id);}
function renderAssignee(){const assigned=state.agents.find(a=>a.id===state.assigneeID);$('assignee-value').textContent=state.assigneeID?(assigned?.name||state.assigneeName||'Unavailable agent'):'Assign agent';renderAgents();}
function renderMetadata(){renderStatus();renderAssignee();$('image-count').textContent=state.attachments.length?String(state.attachments.length):'';renderGallery();}
function renderGallery(){$('gallery').replaceChildren();for(const a of state.attachments){const cell=document.createElement('div');cell.className='attachment';const image=document.createElement('img');image.src=a.url;image.alt=a.filename;image.onclick=()=>{$('image-preview').querySelector('img').src=a.url;$('image-preview').querySelector('img').alt=a.filename;$('image-preview').hidden=false;};const filename=document.createElement('div');filename.className='filename';filename.textContent=a.filename;const actions=document.createElement('div');actions.className='actions';const insert=document.createElement('button');insert.textContent='Insert';insert.onclick=()=>editor.chain().focus().setImage({src:a.url,alt:a.filename}).run();const remove=document.createElement('button');remove.textContent='Remove';remove.onclick=()=>{loading=true;const positions=[];editor.state.doc.descendants((node,pos)=>{if(node.type.name==='image'&&node.attrs.src===a.url)positions.push({pos,size:node.nodeSize});});const tr=editor.state.tr;for(const {pos,size}of positions.reverse())tr.delete(pos,pos+size);editor.view.dispatch(tr);loading=false;state.attachments=state.attachments.filter(i=>i.id!==a.id);post('removeImage',{attachmentID:a.id,title:$('title').value,body:editor.getMarkdown()});renderMetadata();};actions.append(insert,remove);cell.append(image,filename,actions);$('gallery').append(cell);}}
$('title').addEventListener('input',changed);$('close').onclick=()=>post('close');$('status').onclick=()=>togglePicker($('status-picker'),$('status'));$('assignee').onclick=()=>togglePicker($('agent-picker'),$('assignee'),{refresh:true,focusSearch:true});$('agent-search').oninput=renderAgents;$('create-agent').onclick=()=>post('createAgent');$('add-images').onclick=()=>post('pickImages',{inline:false});$('close-image').onclick=()=>{$('image-preview').hidden=true;};$('reload').onclick=()=>post('reload');$('keep').onclick=()=>post('keep');
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.select-shell'))closeSelects();});
for(const trigger of [$('status'),$('assignee')])trigger.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','Enter',' '].includes(e.key)){e.preventDefault();const picker=trigger===$('status')?$('status-picker'):$('agent-picker');if(picker.hidden)openPicker(picker,trigger,{refresh:trigger===$('assignee')});const options=[...picker.querySelectorAll('.select-option')];(e.key==='ArrowUp'?options.at(-1):options.find(i=>i.getAttribute('aria-selected')==='true')||options[0])?.focus();}});
for(const picker of [$('status-picker'),$('agent-picker')])picker.addEventListener('keydown',e=>{const options=[...picker.querySelectorAll('.select-option')];const index=options.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();options[(index+(e.key==='ArrowDown'?1:-1)+options.length)%options.length]?.focus();}else if(e.key==='Home'||e.key==='End'){e.preventDefault();(e.key==='Home'?options[0]:options.at(-1))?.focus();}});
for(const id of ['gallery','image-hint']){$(id).addEventListener('dragover',e=>e.preventDefault());$(id).addEventListener('drop',e=>{e.preventDefault();importFiles(e.dataTransfer.files,false);});}
const linkInput=document.createElement('input');linkInput.placeholder='https://…';linkInput.setAttribute('aria-label','Link address');linkInput.hidden=true;$('toolbar').append(linkInput);linkInput.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const href=linkInput.value.trim();if(/^https?:\/\//i.test(href))editor.chain().focus().extendMarkRange('link').setLink({href}).run();else if(!href)editor.chain().focus().unsetLink().run();linkInput.hidden=true;}};
$('toolbar').onclick=e=>{const b=e.target.closest('button');if(!b)return;const c=b.dataset.command;if(c==='image'){post('pickImages',{inline:true});return;}if(c==='link'){linkInput.hidden=false;linkInput.value=editor.getAttributes('link').href||'';linkInput.focus();return;}const chain=editor.chain().focus();({bold:()=>chain.toggleBold(),italic:()=>chain.toggleItalic(),strike:()=>chain.toggleStrike(),heading:()=>chain.toggleHeading({level:2}),bulletList:()=>chain.toggleBulletList(),orderedList:()=>chain.toggleOrderedList(),taskList:()=>chain.toggleTaskList(),blockquote:()=>chain.toggleBlockquote(),codeBlock:()=>chain.toggleCodeBlock()}[c]?.())?.run();};
document.addEventListener('keydown',e=>{if(e.key==='Tab'){
const scope=$('image-preview').hidden?document:$('image-preview');
const items=[...scope.querySelectorAll('button,input,a[href],[contenteditable="true"]')].filter(el=>!el.disabled&&!el.closest('[hidden]'));
const first=items[0],last=items.at(-1);
if(e.shiftKey&&(document.activeElement===first||!items.includes(document.activeElement))){e.preventDefault();last?.focus();}
else if(!e.shiftKey&&(document.activeElement===last||!items.includes(document.activeElement))){e.preventDefault();first?.focus();}
}if(e.key==='Escape'){e.preventDefault();if(!$('image-preview').hidden)$('image-preview').hidden=true;else if(!$('status-picker').hidden)closePicker($('status-picker'),$('status'),true);else if(!$('agent-picker').hidden)closePicker($('agent-picker'),$('assignee'),true);else post('close');}});
window.taskEditor={load(s){loading=true;state=s;$('title').value=s.title;editor.commands.setContent(s.body,{contentType:'markdown',emitUpdate:false});loading=false;renderMetadata();},metadata(s){state={...state,...s};renderMetadata();},saved(){showError('');$('save-status').textContent='Saved';$('conflict').hidden=true;},error(message,conflict=false){showError(message);$('save-status').textContent='Not saved';$('conflict').hidden=!conflict;},imageImported(a,inline){state.attachments.push(a);renderMetadata();if(inline)editor.chain().focus().setImage({src:a.url,alt:a.filename}).run();else changed();},theme(colors){for(const [k,v]of Object.entries(colors))document.documentElement.style.setProperty('--'+k,v);document.documentElement.style.colorScheme=colors.mode||'dark';},snapshot(){return {title:$('title').value,body:editor.getMarkdown(),attachments:state.attachments};}};
post('ready');
