import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
test('editor controls emit typed native bridge messages and keep initial content quiet',()=>{
 const html=readFileSync(new URL('../src/index.html',import.meta.url),'utf8');
 const dom=new JSDOM(html,{url:'file:///TaskEditor/index.html',runScripts:'outside-only',pretendToBeVisual:true});
 const messages=[]; const w=dom.window;
 w.webkit={messageHandlers:{taskEditor:{postMessage:m=>messages.push(m)}}};
 w.eval(readFileSync(new URL('../../../Sources/ContinuumRevived/Resources/TaskEditor/editor.js',import.meta.url),'utf8'));
 assert.equal(messages[0].type,'ready');
 w.taskEditor.load({title:'Task',body:'**Context**',attachments:[],columns:[{id:'todo',name:'To do'},{id:'done',name:'Done'}],columnID:'todo',agents:[{id:'agent',name:'Layout agent',detail:'Current zone'}],assigneeID:null});
 assert.equal(messages.length,1,'load must not autosave a normalized document');
 assert.equal(w.document.querySelectorAll('select').length,0,'task metadata must never fall back to a native select');
 assert.equal(w.document.querySelectorAll('.select-trigger .choice-chevron').length,2,'both triggers use the shared two-way choice chevron');
 assert.equal(w.document.querySelector('.choice-chevron path').getAttribute('d'),'M3 4 6 1.5 9 4M3 8 6 10.5 9 8');
 const assignee=w.document.getElementById('assignee'); assignee.click();
 assert.equal(assignee.getAttribute('aria-expanded'),'true');
 assert.equal(w.document.getElementById('agent-picker').hidden,false);
 w.document.getElementById('agent-options').children[1].click();
 assert.equal(messages.at(-1).type,'assign'); assert.equal(messages.at(-1).agentID,'agent');
 assert.equal(w.document.getElementById('assignee-value').textContent,'Layout agent');
 const status=w.document.getElementById('status'); status.click();
 assert.equal(status.getAttribute('aria-expanded'),'true');
 assert.equal(w.document.getElementById('status-picker').hidden,false);
 w.document.getElementById('status-options').children[1].click();
 assert.equal(messages.at(-1).columnID,'done');
 assert.equal(w.document.getElementById('status-value').textContent,'Done');
 assert.equal(w.document.getElementById('status-options').children[1].getAttribute('aria-selected'),'true');
 w.document.getElementById('title').value='Edited';w.document.getElementById('title').dispatchEvent(new w.Event('input'));
 assert.equal(messages.at(-1).type,'change'); assert.equal(messages.at(-1).title,'Edited'); assert.equal(messages.at(-1).body,'**Context**');
 dom.window.close();
});
