import ContinuumRevivedCore
import ContinuumRevivedSync
import Foundation

// Ticket: docs/38-tickets/06-oplog-apply-compaction.md — "How we test it / Backend"
//
// Exercises `materialize` against a REAL `ProjectStore` round-trip on disk —
// not a tmux daemon, not a cloud transport. Proves the output of
// `materialize` is valid input to the existing persistence layer, and that
// the op-log faithfully reproduces the committed on-disk fixture.

private func fixtureURL(_ name: String) -> URL {
    URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/ContinuumRevivedSyncChecks/Fixtures", isDirectory: true)
        .appendingPathComponent(name, isDirectory: false)
}

func runOpLogBackendChecks() throws {
    let opsURL = fixtureURL("baseline_ops.json")
    let canvasURL = fixtureURL("canvas.json")

    guard let opsData = try? Data(contentsOf: opsURL) else {
        fputs("FAIL: backend: could not read fixture \(opsURL.path) from cwd \(FileManager.default.currentDirectoryPath)\n", stderr)
        exit(1)
    }
    guard let canvasData = try? Data(contentsOf: canvasURL) else {
        fputs("FAIL: backend: could not read fixture \(canvasURL.path) from cwd \(FileManager.default.currentDirectoryPath)\n", stderr)
        exit(1)
    }

    let baselineOps = try JSONCodec.makeDecoder().decode([LoggedOp].self, from: opsData)
    let fixtureCanvas = try JSONCodec.makeCanvasDecoder().decode(CanvasState.self, from: canvasData)

    // materialize(baseline_ops) must reproduce the committed fixture exactly
    // (schemaVersion/viewport/runtimeRef are excluded from sync per D3/I5).
    //
    // LIMITATION, stated honestly: `canvas.json` and `baseline_ops.json` are
    // both HAND-AUTHORED to match each other — neither was generated by
    // running `materialize` and saving its output. `materialize` never
    // carries `Op`-model metadata (the `Op` enum defined by ticket 02 has no
    // metadata payload on any case), so every tile `materialize` produces
    // always has `metadata: TileMetadata()` (empty). The fixture's tiles are
    // authored with empty `metadata: {}` for exactly that reason. This
    // equality proves frame/title/kind/zPosition/zoneId/groups round-trip
    // faithfully; it does NOT prove `metadata` survives an op-log round-trip
    // against a real canvas.json that carries non-empty metadata — a real
    // fixture with populated metadata would fail this assertion. That gap is
    // the op model's (ticket 02's), not this ticket's, to close.
    let baseline = materialize(ops: baselineOps)
    expect(baseline.canvasState == fixtureCanvas, "backend: materialize(baseline_ops) must reproduce the committed canvas.json fixture exactly")
    expect(baseline.canvasState.tiles.allSatisfy { $0.runtimeRef == nil }, "backend: fixture round-trip carries no runtimeRef")

    // The same `baseline_ops.json` also carries a `createZone` + `setTileZone`
    // pair (the fixture's tile 1 is placed in "Fixture Zone"), so the
    // materialized `workspaceDocument` reproduces a committed `workspace.json`
    // fixture the same way `canvasState` reproduces `canvas.json` above —
    // proving zones round-trip through the op log, not just tiles.
    let workspaceURL = fixtureURL("workspace.json")
    guard let workspaceData = try? Data(contentsOf: workspaceURL) else {
        fputs("FAIL: backend: could not read fixture \(workspaceURL.path) from cwd \(FileManager.default.currentDirectoryPath)\n", stderr)
        exit(1)
    }
    let fixtureWorkspace = try JSONCodec.makeCanvasDecoder().decode(WorkspaceDocument.self, from: workspaceData)
    expect(baseline.workspaceDocument == fixtureWorkspace, "backend: materialize(baseline_ops) must reproduce the committed workspace.json fixture exactly")
    expect(!baseline.workspaceDocument.zones.isEmpty, "backend: fixture round-trip must actually reproduce zone state, not vacuously pass on an empty zones array")
    expect(baseline.workspaceDocument.ambientTiles.isEmpty, "backend: ambientTiles is deliberately left empty by materialize (see OpLog.swift resolve()) — the fixture must not silently start carrying a duplicate tile copy")

    // Append a createTile + a setTileFrame targeting an EXISTING fixture
    // tile, materialize the extended log, and save/load it through the real
    // AtomicWriter-backed ProjectStore — proving materialize's output is
    // valid input to the existing persistence layer.
    guard let existingTileId = fixtureCanvas.tiles.first?.id else {
        fputs("FAIL: backend: fixture canvas.json must contain at least one tile\n", stderr)
        exit(1)
    }
    let newTileId = UUID(uuidString: "9999999A-0000-4000-8000-000000000099")!
    let lastOpId = baselineOps.map(\.opId).max()!
    let extendedOps = baselineOps + [
        LoggedOp(
            opId: OpId(lamport: lastOpId.lamport + 1, replica: lastOpId.replica),
            // Sizes chosen at/above CanvasEngine's persisted-load minimums for
            // these kinds (browser: 320x220, terminal: 180x124) so
            // `loadCanvas`'s sanitization pass is a no-op and the round-trip
            // assertion below compares exact, unmodified frames.
            op: .createTile(
                id: newTileId, kind: .browser, title: "appended",
                frame: TileFrame(x: 1000, y: 1000, width: 400, height: 300),
                zPosition: FracIndex(value: 0.9)
            )
        ),
        LoggedOp(
            opId: OpId(lamport: lastOpId.lamport + 2, replica: lastOpId.replica),
            op: .setTileFrame(id: existingTileId, frame: TileFrame(x: 42, y: 42, width: 300, height: 200))
        ),
    ]
    let extended = materialize(ops: extendedOps)
    expect(extended.canvasState.tiles.contains(where: { $0.id == newTileId }), "backend: appended createTile must be present in the extended materialize")
    expect(
        extended.canvasState.tiles.first(where: { $0.id == existingTileId })?.frame == TileFrame(x: 42, y: 42, width: 300, height: 200),
        "backend: appended setTileFrame must win over the fixture's original frame for the existing tile"
    )

    let tmpRoot = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
    defer { try? FileManager.default.removeItem(at: tmpRoot) }
    let store = ProjectStore(projectRoot: tmpRoot)
    try store.saveCanvas(extended.canvasState)
    let loadedBack = try store.loadCanvas()
    expect(loadedBack == extended.canvasState, "backend: ProjectStore.saveCanvas → loadCanvas must round-trip materialize's output byte-for-byte (struct-equal)")

    // Same proof for `WorkspaceStore` — append a `setZoneName` targeting the
    // fixture's real zone, materialize, and round-trip the resulting
    // `workspaceDocument` (zones + the deliberately-empty ambientTiles)
    // through the real `AtomicWriter`-backed `WorkspaceStore`, not a mock.
    guard let existingZoneId = fixtureWorkspace.zones.first?.zoneId else {
        fputs("FAIL: backend: fixture workspace.json must contain at least one zone\n", stderr)
        exit(1)
    }
    let extendedWorkspaceOps = baselineOps + [
        LoggedOp(
            opId: OpId(lamport: lastOpId.lamport + 3, replica: lastOpId.replica),
            op: .setZoneName(id: existingZoneId, name: "renamed via op log")
        ),
    ]
    let extendedWorkspace = materialize(ops: extendedWorkspaceOps).workspaceDocument
    expect(
        extendedWorkspace.zones.first(where: { $0.zoneId == existingZoneId })?.name == "renamed via op log",
        "backend: appended setZoneName must win over the fixture's original zone name"
    )

    let workspaceTmpRoot = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
    defer { try? FileManager.default.removeItem(at: workspaceTmpRoot) }
    let workspaceStore = WorkspaceStore(workspaceId: UUID(), applicationSupportDirectory: workspaceTmpRoot)
    try workspaceStore.save(extendedWorkspace)
    let loadedWorkspaceBack = try workspaceStore.load()
    expect(loadedWorkspaceBack == extendedWorkspace, "backend: WorkspaceStore.save → load must round-trip materialize's workspaceDocument output byte-for-byte (struct-equal), including zones and the deliberately-empty ambientTiles")

    print("oplog backend: baseline fixture (canvas + workspace) reproduced exactly, appended ops + real ProjectStore.saveCanvas/loadCanvas and WorkspaceStore.save/load round-trips clean")
}
